'use strict';
// No packages or real browser storage required: exercise the shipped functions.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const projectRoot = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(projectRoot, 'app.js'), 'utf8');
const i18n = fs.readFileSync(path.join(projectRoot, 'i18n.js'), 'utf8');
const css = fs.readFileSync(path.join(projectRoot, 'style.css'), 'utf8');
const html = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(projectRoot, 'manifest.webmanifest'), 'utf8'));
new vm.Script(source);
function section(start, end) {
  const from = source.indexOf(start), to = source.indexOf(end, from + start.length);
  assert(from >= 0 && to > from, 'Test source boundary exists');
  return source.slice(from, to);
}
async function run() {
  assert(source.includes('function renderUnifiedEditors('), 'Editors share one renderer');
  assert(source.includes('function bindUnifiedEditor('), 'Editors share one event binder');
  assert.equal((source.match(/function unifiedEditorToolbar\(/g) || []).length, 1, 'Only one editor toolbar implementation exists');
  assert(source.includes("$$('.document-card',$('#canvasWorld')).forEach(element=>element.remove())"), 'Unified render clears the original card before rebuilding editors');
  assert(html.includes('<section class="document-card" id="documentCard"></section>'), 'The primary editor has no duplicate static implementation');
  assert(source.includes('contenteditable="${!state.readingMode}" spellcheck="true" role="textbox" aria-multiline="true"'), 'Each document uses one continuous editable host');
  assert(!source.includes('id="addBlockRow"'), 'The obsolete Add block row is removed');
  assert(source.includes("editor.addEventListener('beforeinput'"), 'Typing history snapshots are captured before text mutates');
  assert(source.includes("if((!editing||noteEditing)&&event.ctrlKey&&event.key.toLowerCase()==='z')"), 'Ctrl+Z is handled consistently inside and outside the document editor');
  assert(source.includes('restoreHistoryFocus(focus)'), 'Undo and redo restore the active editor caret');
  assert(!html.includes('id="imageInput"'), 'Obsolete global image input is removed');
  assert(html.includes('rel="manifest" href="manifest.webmanifest?v=5"'), 'Page declares its versioned PWA manifest');
  assert.equal(manifest.name, 'Ramizom PowerMind');
  assert.equal(manifest.short_name, 'PowerMind');
  assert.equal(manifest.description, 'A visual note workspace for blocks, mind maps, and handwriting.');
  assert(Array.isArray(manifest.icons) && manifest.icons.length > 0, 'Manifest declares install icons');
  const allowedPurposes = new Set(['any', 'maskable', 'monochrome']);
  manifest.icons.forEach(icon => {
    assert(icon.src && icon.type && icon.sizes, `Manifest icon is fully described: ${icon.src}`);
    const purposes = String(icon.purpose || 'any').trim().split(/\s+/);
    purposes.forEach(purpose => assert(allowedPurposes.has(purpose), `Manifest icon purpose is valid: ${purpose}`));
    assert(fs.existsSync(path.join(projectRoot, icon.src.split('?')[0].replace(/^\.\//, ''))), `Manifest icon file exists: ${icon.src}`);
  });
  assert(manifest.icons.every(icon => !String(icon.purpose || '').includes('any') || !String(icon.purpose || '').includes('maskable')), 'Rounded brand art is not also declared maskable');
  assert(manifest.icons.every(icon => !String(icon.purpose || '').includes('maskable')), 'The rounded brand silhouette is used consistently instead of a square maskable fallback');
  assert(html.includes('rel="apple-touch-icon" href="apple-touch-icon.png?v=5"'), 'Page declares a versioned Apple touch icon');
  assert(html.includes('id="unsupportedGate"'), 'An unsupported-platform gate exists before the app boots');
  assert(html.includes('id="unsupportedReason"'), 'The unsupported-platform gate explains the reason');
  assert(html.includes('id="unsupportedLanguage"'), 'The unsupported-platform gate offers a language selector');
  ['unsupportedTitle','unsupportedBody','unsupportedInsecure','unsupportedSupportedLabel','unsupportedDesktop','unsupportedAndroid','unsupportedUnavailable'].forEach(key => {
    assert.equal((i18n.match(new RegExp(`${key}\\s*:`, 'g')) || []).length, 8, `Unsupported-platform copy is translated into all 8 languages: ${key}`);
    assert(html.includes(`data-i18n="${key}"`) || key === 'unsupportedInsecure', `Unsupported-platform copy is wired into the page: ${key}`);
  });
  assert(source.includes("typeof window.showDirectoryPicker === 'function'"), 'Storage support is detected before the app boots');
  assert(source.includes("location.protocol === 'file:'"), 'Opening the app from file:// is treated as unsupported');
  assert(source.includes('function flushPendingSave('), 'A pending debounced save can be flushed on demand');
  assert(source.includes('state.changeRevision>state.savedRevision'), 'Exiting also queues a save when the newest revision is still pending');
  assert(source.includes('if(revision===state.changeRevision)'), 'Saved status is shown only after the current edit revision reaches disk');
  assert(source.includes('function restoreLastOpen()'), 'The last opened workspace and note are restored deterministically');
  assert(source.includes('lastOpened:db.lastOpened||null'), 'The current workspace and note are also written with the folder manifest');
  assert(source.includes('async saveLastOpened(lastOpened)'), 'Changing notes writes the last-opened location back to the workspace manifest');
  assert(source.includes("document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushPendingSave();})"), 'Burying the page flushes the pending save');
  assert(source.includes("addEventListener('pagehide',flushPendingSave)"), 'Tearing down the page flushes the pending save');
  assert(source.includes('state.saveTimer=setTimeout(()=>{state.saveTimer=null;scheduleSave(true);},450)'), 'The save debounce clears its own timer so a flush can detect pending work');
  const headBoot = html.indexOf('window.PM_BOOT={');
  const bodyBoot = html.indexOf("classList.add(boot.dark?'theme-dark':'theme-light')");
  assert(headBoot > 0, 'The saved theme is resolved while the head is still being parsed');
  assert(headBoot < html.indexOf('</head>'), 'The theme bootstrap runs before the body is parsed');
  assert(bodyBoot > 0 && bodyBoot < html.indexOf('class="startup-splash"'), 'Body theme classes land before the splash markup, so the first paint is already themed');
  assert(html.includes('media="(prefers-color-scheme: dark)"'), 'A static theme colour follows the OS scheme before any script runs');
  assert(source.includes("meta.removeAttribute('media')"), 'The dynamic theme colour takes over the static metas');
  assert(source.includes('requestPersistentStorage'), 'Persistent storage is requested so a remembered folder handle is not evicted');
  assert(source.includes('transaction.oncomplete'), 'Remembering the folder waits for the IndexedDB transaction to commit');
  assert(source.includes("try{await storage.rememberHandle(directory);}catch"), 'A failed handle write cannot abort connecting a folder');
  assert(source.includes("state.mobileStage=isPortraitMobile()?(activeNote()?'editor':'notes'):'editor'"), 'Portrait launch opens the note itself, or the note list when there is no note');
  assert(!source.includes("?'workspace':'editor'"), 'Portrait launch no longer stops on the navigation drawer');
  const fluentOptions = /\.fluent-options \{([^}]*)\}/.exec(css);
  assert(fluentOptions, 'The fluent picker panel has a base rule');
  assert(/\bbottom\s*:/.test(fluentOptions[1]), 'The picker panel base rule pins its own bottom edge so a stray inset cannot collapse it');
  assert(!/\.fluent-options[^{]*\{[^}]*position\s*:\s*fixed/.test(css), 'No picker panel override can leak a fixed inset into the base rule');
  assert(!source.includes('serviceWorker')&&!fs.existsSync(path.join(projectRoot,'sw.js')), 'The installable app has no service worker or application cache');
  assert(html.includes('manifest.webmanifest?v=5') && html.includes('style.css?v=5') && html.includes('app.js?v=5'), 'Updated app resources receive a cache version');
  assert(css.includes('background:url("icon.svg?v=5")'), 'Startup and folder-gate marks reuse the rounded installed-app icon');
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length, 'Static HTML IDs are unique');
  const localAssets = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(match => match[1].split('?')[0]).filter(value => value && !value.startsWith('#') && !/^[a-z]+:/i.test(value));
  localAssets.forEach(asset => assert(fs.existsSync(path.join(projectRoot, asset)), `Local asset exists: ${asset}`));
  assert(source.includes('const detectedLanguage = () =>'), 'Browser language is detected before a preference is saved');
  assert(source.includes("$('#collapseNav').onclick=toggleNavigationAndNotes"), 'The sole hamburger controls the primary and notes panes together');
  assert(source.includes("function toggleNavigationAndNotes(){const shell=$('.app-shell')"), 'Navigation and notes collapse in one atomic action');
  assert(source.includes('function activateNavigationScope(filter,folderId=null)'), 'Navigation items own the notes-pane toggle behavior');
  assert(source.includes("if(!isPortraitMobile()&&isCurrent){togglePane('notes');return;}"), 'Repeated desktop navigation selection toggles the notes pane');
  assert(source.includes("workSlot=$('#workMenuSlot')"), 'The sole hamburger moves into the editor after navigation is collapsed');
  assert(source.includes('function updateNoteCommandAvailability('), 'Selecting a newly created note refreshes command availability');
  assert(source.includes('updateNoteCommandAvailability(true);'), 'Newly selected notes immediately enable their note commands');
  assert(source.includes('function printInkDataUrl(note)'), 'Print output uses a dedicated ink renderer');
  assert(source.includes('drawStroke(context,stroke,1,false)'), 'Print ink resolves adaptive colors for a light paper background');
  assert(source.includes('if(vectors.length)vectors.forEach'), 'Print prefers theme-independent vector ink over the dark screen raster');
  assert(source.includes('normalizePrintTextColors(scene)'), 'Print converts explicit white editor text for a light paper background');
  assert(css.includes('color-scheme:light') && css.includes('background:#fff!important'), 'Print cards use a theme-independent light paper palette');
  assert(source.includes('function resumeRememberedFolder()'), 'A remembered folder can be reopened without showing the picker');
  const editorMarkup = section('  function unifiedEditorBlockMarkup(', '  function openUnifiedSlashMenu(');
  assert(!editorMarkup.includes('secondary-block-handle') && !editorMarkup.includes('data-editor-delete'), 'Editor markup has no per-block drag or delete chrome');
  assert(!html.includes('id="openNotesMobile"') && !html.includes('id="openNav"'), 'Redundant hamburger buttons are removed');
  assert(source.includes('class="menu-check"'), 'Sort selection uses an icon checkmark, not a text character');
  let sequence = 0;
  const context = vm.createContext({
    id: () => `test-${++sequence}`, clone: value => JSON.parse(JSON.stringify(value)),
    state: {}, updateStorageLabel() {}, console,
    localStorage: { getItem: () => null, setItem() { throw new Error('Quota'); } },
    navigator: { storage: { getDirectory: async () => { throw new Error('Unavailable'); } } }
  });
  vm.runInContext(section('  function copyImportedNote(', '  async function importBackup('), context);
  const original = { id:'n', blocks:[{id:'b', text:'正文'}], ideas:[{id:'root',root:true},{id:'child',parentId:'root'}], editors:[{id:'e',blocks:[{id:'eb',text:'second editor'}]}], inkStrokes:[{id:'ink',points:[]}] };
  const imported = context.copyImportedNote(original, 'workspace', 'folder');
  assert.equal(imported.ideas[1].parentId, imported.ideas[0].id);
  assert.notEqual(imported.ideas[0].id, 'root');
  assert.notEqual(imported.editors[0].blocks[0].id, 'eb');
  assert.equal(original.ideas[1].parentId, 'root', 'Source backup remains unchanged');
  assert.equal(imported.editors[0].blocks[0].text, 'second editor');
  assert.equal(context.copyImportedNote({id:'minimal'}, 'w', 'f').workspaceId, 'w');
  context.clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
  context.safeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#c42b1c';
  context.safeDataImage=value=>/^data:image\/(?:png|jpe?g|webp|gif);base64,[a-z0-9+/=\s]+$/i.test(String(value||''))?String(value):'';
  context.sanitizeRichHtml=value=>String(value||'').replace(/<img[^>]*>/gi,'').replace(/\s+onclick=(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'');
  context.t=key=>key;
  context.normalizedId=(value,used)=>{let next=value||context.id();while(used.has(next))next=context.id();used.add(next);return next;};
  vm.runInContext(section('  function findEditorPosition(', '  function firstMindMapPosition('), context);
  vm.runInContext(section('  function migrateDatabase(', '  function applyTranslations('), context);
  const normalized=context.migrateDatabase({version:3,workspaces:[{id:'w'}],folders:[{id:'f',workspaceId:'w'}],notes:[{id:'n',workspaceId:'w',folderId:'f',ink:'https://tracker.invalid/pixel.png',blocks:[{id:'b',type:'bad" onclick="alert(1)',color:'red" onmouseover="x',html:'<img src=x onerror=alert(1)><b onclick=alert(2)>safe</b>'},{id:'image',type:'image',src:'https://tracker.invalid/image.png'}],ideas:[{id:'r',root:true},{id:'a',parentId:'c'},{id:'c',parentId:'a'}]}]});
  assert.equal(normalized.notes[0].blocks[0].type,'text');
  assert.equal(normalized.notes[0].blocks[0].color,undefined);
  assert.equal(normalized.notes[0].blocks[0].html,'<b>safe</b>','Imported rich text is sanitized');
  assert.equal(normalized.notes[0].blocks[1].type,'text','External imported images are rejected');
  assert.equal(normalized.notes[0].ink,null,'External legacy ink images are rejected');
  assert.equal(normalized.notes[0].ideas[1].parentId,'r','Cyclic parent chain repaired');
  assert.equal(normalized.notes[0].card.x,620);
  assert(Array.isArray(normalized.notes[0].editors));
  const layoutNote={card:{x:100,y:100,width:620,height:410},editors:[{id:'e1',x:120,y:120,width:620,height:410,blocks:[]},{id:'e2',x:140,y:140,width:620,height:410,blocks:[]}]};
  context.repairEditorOverlaps(layoutNote);
  const boxes=[{x:100,y:100,width:620,height:410},...layoutNote.editors];
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert(boxes[i].x+boxes[i].width<=boxes[j].x||boxes[j].x+boxes[j].width<=boxes[i].x||boxes[i].y+boxes[i].height<=boxes[j].y||boxes[j].y+boxes[j].height<=boxes[i].y,'Editors do not overlap');
  vm.runInContext(section('  const storage = {', '  function seedDatabase()') + '\nthis.testStorage=storage;', context);
  await assert.rejects(context.testStorage.save({notes:[]}), /Choose a system folder/);
  const makeDirectory=name=>{const entries=new Map();return{name,entries,queryPermission:async()=> 'granted',getDirectoryHandle:async(child,{create}={})=>{if(!entries.has(child)&&create)entries.set(child,makeDirectory(child));if(!entries.has(child))Object.assign(new Error('not found'),{name:'NotFoundError'});return entries.get(child);},getFileHandle:async(file,{create}={})=>{if(!entries.has(file)&&create)entries.set(file,{kind:'file',name:file,text:''});const record=entries.get(file);if(!record)throw Object.assign(new Error('not found'),{name:'NotFoundError'});return{getFile:async()=>({text:async()=>record.text}),createWritable:async()=>({write:async value=>{record.text=value;},close:async()=>{}})};},values:async function*(){for(const entry of entries.values())yield entry;},removeEntry:async key=>entries.delete(key)};};
  const directory=makeDirectory('Notes');context.state.directoryHandle=directory;
  const db={savedAt:20,notes:[{id:'recent',fileName:'Visible file',title:'Independent editor title'}],workspaces:[{id:'w'}],folders:[]};
  await context.testStorage.save(db);
  assert(directory.entries.has('powermind.workspace.json'),'Manifest is visible in selected folder');
  assert([...directory.entries.get('notes').entries.keys()].some(name=>name.includes('Visible file')&&name.endsWith('.powermind.json')),'Each note has a readable visible filename');
  const loaded=await context.testStorage.loadDirectory(directory);
  assert.equal(loaded.notes[0].fileName,'Visible file','Folder workspace round-trips the independent note filename');
  assert.equal(loaded.notes[0].title,'Independent editor title','Editor title remains independent from the note filename');
  vm.runInContext(section('  function pointInPolygon(', '  function resolveInkColor('), context);
  const square=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];
  assert.equal(context.pointInPolygon({x:5,y:5},square),true);
  assert.equal(context.pointInPolygon({x:15,y:5},square),false);
  // --- Touch ink cost: Android gets a smaller buffer, Windows keeps the pen contract byte for byte ---
  assert(source.includes("function coarsePointer(){return matchMedia('(pointer:coarse)').matches;}"), 'Touch-only devices are identified through one shared helper');
  assert(source.includes("quality=canvas.id==='inkOverlay'?(touch?.6:1):clamp((window.devicePixelRatio||1)*state.view.zoom,1,touch?1:1.25)"), 'Touch devices cap the ink buffer at 1:1 while pen devices keep the sharper 1.25 cap');
  assert(html.includes('<canvas id="inkCanvas" width="1" height="1">'), 'The ink backing store is allocated on demand instead of at parse time');
  assert(html.includes('<canvas id="inkOverlay" width="1" height="1"'), 'The lasso overlay backing store is allocated on demand instead of at parse time');
  assert(/#inkCanvas\s*\{[^}]*width:\s*4000px[^}]*height:\s*3000px/.test(css), 'The ink canvas keeps its world-sized CSS box so a small backing store still covers the canvas');
  assert(/#inkOverlay\s*\{[^}]*width:\s*4000px[^}]*height:\s*3000px/.test(css), 'The overlay keeps its world-sized CSS box so a small backing store still covers the canvas');
  assert(source.includes("if(!hasContent){box.hidden=true;if(canvas.dataset.painted!=='1')return;"), 'Repainting the overlay is skipped entirely while nothing is painted on it');
  assert(source.includes("const painted=state.inkSelection.size>0||$('#inkOverlay').dataset.painted==='1'"), 'Starting a stroke only clears the overlay when something is painted on it');
  assert(source.includes('const rect=inkCanvasRect||(inkCanvasRect=canvas.getBoundingClientRect())'), 'Ink sampling reuses cached canvas bounds instead of forcing layout for every sample');
  assert(source.includes('strokeTouch=coarse;inkCanvasRect=canvas.getBoundingClientRect();'), 'The cached ink bounds are refreshed once per stroke');
  assert(source.includes('inkCanvasRect = null;'), 'Pan, zoom and fit invalidate the cached ink bounds');
  assert(source.includes('palmLimit=coarse?140:24'), 'Finger contacts draw on touch-only devices while pen-first devices keep the original 24px palm rule');
  assert(source.includes("minimum=source.pointerType==='pen'?.22:strokeTouch?1.2:.7"), 'The pen keeps its dense .22 sampling while touch strokes filter wider');
  assert(source.includes("if(event.pointerType==='mouse')updateInkCursor(event)"), 'Ink cursor styling is only touched by a mouse');
  assert(source.includes('coordinateFrame=requestAnimationFrame('), 'The canvas coordinate read-out is coalesced into one frame');
  // --- Mind map: selectable and draggable as a whole ---
  assert(source.includes('function ideaDragGroup(idea, note)'), 'The mind map has an explicit drag-group helper');
  assert(source.includes('if (!idea?.root) return null;'), 'Only the map root carries the whole map, so single nodes keep free positioning');
  assert(source.includes('group:()=>ideaDragGroup(idea,note)'), 'Idea nodes are wired to group dragging');
  assert(source.includes('options.onPointerDown?.(event)'), 'A drag can select its object before movement');
  assert(source.includes("onPointerDown:()=>selectObject('idea',idea.id,element)"), 'Grabbing an idea selects it, because preventDefault suppresses the follow-up click');
  assert(source.includes("window.addEventListener('pointermove',move,{passive:true})"), 'A drag tracks on window so a dropped pointer capture cannot strand a node');
  assert(source.includes('if(pointer.pointerId!==dragId)return;'), 'A stray second pointer cannot drive an active drag');
  assert(source.includes("window.removeEventListener('pointermove',move)"), 'Drag listeners are always removed when the drag ends');
  assert(!source.includes("element.addEventListener('pointermove',move)"), 'No drag binds its move handler to the dragged element');
  assert(css.includes('.idea-node.dragging {') && css.includes('.idea-node.group-dragging {'), 'Dragging a node or its whole map is visible');
  console.log('PASS: syntax, unified editor path, import tree/IDs/content/source isolation, missing optional fields, system-folder storage, ink geometry, touch/pen ink cost split, mind-map group drag');
}
module.exports = run;
if (require.main === module) run().catch(error => { console.error(error); process.exitCode = 1; });
