'use strict';
// No packages or real browser storage required: exercise the shipped functions.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const projectRoot = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(projectRoot, 'app.js'), 'utf8');
const i18n = fs.readFileSync(path.join(projectRoot, 'i18n.js'), 'utf8');
const css = fs.readFileSync(path.join(projectRoot, 'style.css'), 'utf8');
const html = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(projectRoot, 'manifest.webmanifest'), 'utf8'));
const i18nContext={window:{}};
vm.createContext(i18nContext);
vm.runInContext(i18n,i18nContext);
const repositoryTextExtensions = new Set(['.js','.cjs','.html','.css','.md','.json','.webmanifest','.yml','.yaml']);
function repositoryTextFiles(directory=projectRoot) {
  const files=[];
  for(const entry of fs.readdirSync(directory,{withFileTypes:true})){
    if(entry.isDirectory()&&['.git','.tmp','.cache','.temp','.history','.playwright','.agents','.codex','.claude','node_modules','notes','dist','out','coverage','playwright-report','test-results','screenshots'].includes(entry.name))continue;
    const absolute=path.join(directory,entry.name);
    if(entry.isDirectory())files.push(...repositoryTextFiles(absolute));
    else if(repositoryTextExtensions.has(path.extname(entry.name))||['LICENSE','.gitignore'].includes(entry.name))files.push(absolute);
  }
  return files;
}
new vm.Script(source);
function section(start, end) {
  const from = source.indexOf(start), to = source.indexOf(end, from + start.length);
  assert(from >= 0 && to > from, 'Test source boundary exists');
  return source.slice(from, to);
}
async function run() {
  const hanScript=/[\u3400-\u9fff]/u;
  repositoryTextFiles().filter(file=>path.basename(file)!=='i18n.js').forEach(file=>assert(!hanScript.test(fs.readFileSync(file,'utf8')),`Non-localization source remains English: ${path.relative(projectRoot,file)}`));
  assert.equal((i18n.match(/defaultInbox:/g)||[]).length,8,'Localized starter content covers all supported languages');
  assert(i18n.includes('window.PM_LANGUAGE_NAMES'), 'Native language names live in the localization module');
  const localeTables=i18nContext.window.PM_I18N,englishKeys=Object.keys(localeTables.en);
  Object.entries(localeTables).forEach(([locale,table])=>assert.deepEqual(englishKeys.filter(key=>!(key in table)),[],`Locale covers every English key: ${locale}`));
  assert(fs.readFileSync(path.join(projectRoot,'LICENSE'),'utf8').startsWith('MIT License'), 'The repository includes an MIT license');
  assert(fs.readFileSync(path.join(projectRoot,'README.md'),'utf8').includes('AI development disclosure'), 'The README discloses substantial AI assistance');
  const packageMetadata=JSON.parse(fs.readFileSync(path.join(projectRoot,'package.json'),'utf8'));
  assert.equal(packageMetadata.scripts.build,'node tools/build.cjs','Static hosts have a deterministic production build command');
  assert.equal(packageMetadata.scripts['deploy:cloudflare'],'npx wrangler deploy --config wrangler.jsonc','Workers deploy through the checked-in configuration');
  const wranglerConfig=JSON.parse(fs.readFileSync(path.join(projectRoot,'wrangler.jsonc'),'utf8'));
  assert.equal(wranglerConfig.assets.directory,'.','Workers serve the dependency-free application directly from the repository root');
  assert.equal(wranglerConfig.send_metrics,false,'Wrangler telemetry is disabled for this project');
  const assetIgnore=fs.readFileSync(path.join(projectRoot,'.assetsignore'),'utf8');
  assert(assetIgnore.startsWith('# Publish only')&&assetIgnore.includes('\n*\n'),'Root asset deployment uses a deny-by-default allowlist');
  ['index.html','app.js','i18n.js','style.css','manifest.webmanifest'].forEach(file=>assert(assetIgnore.includes(`!${file}`),`Root asset allowlist includes ${file}`));
  assert(fs.readFileSync(path.join(projectRoot,'tools','build.cjs'),'utf8').includes("'index.html'"),'The production build explicitly includes the application entry point');
  assert(fs.readFileSync(path.join(projectRoot,'tools','build.cjs'),'utf8').includes('cloudflareAssetLimit'),'The production build rejects assets above Cloudflare\'s per-file limit');
  assert(fs.readFileSync(path.join(projectRoot,'_headers'),'utf8').includes('Content-Security-Policy:'),'Cloudflare Pages receives baseline security headers');
  assert(source.includes('function renderUnifiedEditors('), 'Editors share one renderer');
  assert(source.includes('function bindUnifiedEditor('), 'Editors share one event binder');
  assert.equal((source.match(/function unifiedEditorToolbar\(/g) || []).length, 1, 'Only one editor toolbar implementation exists');
  assert(source.includes("$$('.document-card',$('#canvasWorld')).forEach(element=>element.remove())"), 'Unified render clears the original card before rebuilding editors');
  assert(html.includes('<section class="document-card" id="documentCard"></section>'), 'The primary editor has no duplicate static implementation');
  assert(source.includes('contenteditable="${!state.readingMode}" spellcheck="true" role="textbox" aria-multiline="true"'), 'Each document uses one continuous editable host');
  assert(source.includes("'S','STRIKE','DEL'"), 'Strike-through markup survives sanitizing, saving, and re-rendering');
  assert(source.includes("document.execCommand('styleWithCSS',false,false)"), 'Inline formatting commands prefer stable semantic tags');
  assert(source.includes("'A','FONT','BR','CODE','SPAN'"), 'Links and code markup remain supported by the compatibility sanitizer');
  assert(source.includes("[data-editor-link]") && source.includes("document.execCommand('createLink'"), 'The link command uses the continuous editor selection');
  assert(source.includes("prepareNoteImage(image,properties=>add('image'"), 'Image paste is inserted through the note model instead of raw editable HTML');
  assert(source.includes("if(type==='image'){const following=record.blocks[insertIndex+1]"), 'Every image insertion resolves an editable destination after the image');
  assert(source.includes("focusBlock=createEditorBlock('text')"), 'An image inserted at the document end creates a trailing paragraph');
  assert(source.includes("blocks[index].type==='image'&&(!blocks[index+1]"), 'Existing notes migrate end-position images to an editable trailing paragraph');
  assert(!source.includes('data-editor-add="code"'), 'Code insertion is removed from the editor toolbar');
  assert(!source.includes("'quote','code','formula'"), 'Code insertion is removed from the slash menu');
  assert(!source.includes("'```'"), 'Code fence auto-conversion is removed from editor typing');
  assert(source.includes('function normalizeEditorContent(content)'), 'Generated blockquote wrappers are normalized before saving rich text');
  assert(source.includes("state.guideSnap={type:'ruler',edge:index}"), 'Ruler ink locks to a visible edge instead of its centre line');
  assert(source.includes("state.guideSnap={type:'triangle',edge:edgeIndex}"), 'Triangle ink stays on one edge for the duration of a stroke');
  assert(!source.includes('openTextColorPalette')&&!source.includes('data-editor-color'), 'The retired document text-color setting has no editor code path');
  assert(!html.includes('textColorPalette')&&!css.includes('.color-palette'), 'The retired text-color palette has no UI surface');
  assert(!source.includes('id="addBlockRow"'), 'The obsolete Add block row is removed');
  assert(source.includes('contenteditable="false"'), 'Image, formula, and divider blocks are atomic inside the continuous editor');
  assert(source.includes('const removeAtomic='), 'Backspace and Delete remove atomic editor elements through the note model');
  assert(source.includes('record.blocks.forEach(block=>{const blockElement='), 'Typing alongside media preserves non-text blocks during document synchronization');
  assert(source.includes("list.addEventListener('paste',event=>{event.stopImmediatePropagation()") && source.includes("list.addEventListener('keydown',event=>{event.stopImmediatePropagation()"), 'Continuous editor owns paste and keyboard edits at one stable event boundary');
  assert(source.includes("list.addEventListener('input',event=>{event.stopImmediatePropagation()"), 'Continuous editor synchronizes each text edit exactly once');
  assert(source.includes('if(!list.isConnected||!root.isConnected||state.readingMode)return'), 'Queued input from a replaced editor cannot resurrect stale text after Enter or Backspace');
  assert(source.includes('if(!editor.isConnected||state.readingMode'), 'Detached editor history listeners ignore post-render browser events');
  assert(source.includes("editor.addEventListener('beforeinput'"), 'Typing history snapshots are captured before text mutates');
  assert(source.includes('const commandKey=event.ctrlKey||event.metaKey') && source.includes("commandKey&&event.key.toLowerCase()==='z'"), 'Ctrl/Cmd+Z is handled consistently inside and outside the document editor');
  assert(source.includes('restoreHistoryFocus(focus)'), 'Undo and redo restore the active editor caret');
  assert(!html.includes('id="imageInput"'), 'Obsolete global image input is removed');
  assert(html.includes('rel="manifest" href="manifest.webmanifest?v=26"'), 'Page declares its versioned PWA manifest');
  assert.equal(manifest.name, 'Ramizom PowerMind Preview');
  assert.equal(manifest.short_name, 'PowerMind Preview');
  assert.equal(manifest.description, 'A visual note workspace for blocks, mind maps, and handwriting.');
  assert(Array.isArray(manifest.icons) && manifest.icons.length > 0, 'Manifest declares install icons');
  const allowedPurposes = new Set(['any', 'maskable', 'monochrome']);
  manifest.icons.forEach(icon => {
    assert(icon.src && icon.type && icon.sizes, `Manifest icon is fully described: ${icon.src}`);
    const purposes = String(icon.purpose || 'any').trim().split(/\s+/);
    purposes.forEach(purpose => assert(allowedPurposes.has(purpose), `Manifest icon purpose is valid: ${purpose}`));
    assert(fs.existsSync(path.join(projectRoot, icon.src.split('?')[0].replace(/^\.\//, ''))), `Manifest icon file exists: ${icon.src}`);
  });
  assert(manifest.icons.every(icon => !String(icon.purpose || '').includes('any') || !String(icon.purpose || '').includes('maskable')), 'Rounded brand art is not also declared maskable');
  assert(manifest.icons.every(icon => !String(icon.purpose || '').includes('maskable')), 'The rounded brand silhouette is used consistently instead of a square maskable fallback');
  assert(html.includes('rel="apple-touch-icon" href="apple-touch-icon.png?v=26"'), 'Page declares a versioned Apple touch icon');
  assert(html.includes('id="unsupportedGate"'), 'An unsupported-platform gate exists before the app boots');
  assert(html.includes('id="unsupportedReason"'), 'The unsupported-platform gate explains the reason');
  assert(html.includes('id="unsupportedLanguage"'), 'The unsupported-platform gate offers a language selector');
  ['unsupportedTitle','unsupportedBody','unsupportedInsecure','unsupportedSupportedLabel','unsupportedDesktop','unsupportedAndroid','unsupportedUnavailable'].forEach(key => {
    assert.equal((i18n.match(new RegExp(`${key}\\s*:`, 'g')) || []).length, 8, `Unsupported-platform copy is translated into all 8 languages: ${key}`);
    assert(html.includes(`data-i18n="${key}"`) || key === 'unsupportedInsecure', `Unsupported-platform copy is wired into the page: ${key}`);
  });
  assert(source.includes("typeof window.showDirectoryPicker === 'function'"), 'Storage support is detected before the app boots');
  assert(source.includes("location.protocol === 'file:'"), 'Opening the app from file:// is treated as unsupported');
  assert(source.includes('function flushPendingSave('), 'A pending debounced save can be flushed on demand');
  assert(source.includes('state.changeRevision>state.savedRevision'), 'Exiting also queues a save when the newest revision is still pending');
  assert(source.includes('if(revision===state.changeRevision)'), 'Saved status is shown only after the current edit revision reaches disk');
  assert(source.includes('function restoreLastOpen()'), 'The last opened workspace and note are restored deterministically');
  assert(source.includes('lastOpened:db.lastOpened||null'), 'The current workspace and note are also written with the folder manifest');
  assert(source.includes('async saveLastOpened(lastOpened)'), 'Changing notes writes the last-opened location back to the workspace manifest');
  assert(source.includes("document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushPendingSave();})"), 'Burying the page flushes the pending save');
  assert(source.includes("addEventListener('pagehide',flushPendingSave)"), 'Tearing down the page flushes the pending save');
  assert(source.includes('state.saveTimer=setTimeout(()=>{state.saveTimer=null;scheduleSave(true);},450)'), 'The save debounce clears its own timer so a flush can detect pending work');
  const headBoot = html.indexOf('window.PM_BOOT={');
  const bodyBoot = html.indexOf("classList.add(boot.dark?'theme-dark':'theme-light')");
  assert(headBoot > 0, 'The saved theme is resolved while the head is still being parsed');
  assert(headBoot < html.indexOf('</head>'), 'The theme bootstrap runs before the body is parsed');
  assert(bodyBoot > 0 && bodyBoot < html.indexOf('class="startup-splash"'), 'Body theme classes land before the splash markup, so the first paint is already themed');
  assert(html.includes('media="(prefers-color-scheme: dark)"'), 'A static theme colour follows the OS scheme before any script runs');
  assert(source.includes("meta.removeAttribute('media')"), 'The dynamic theme colour takes over the static metas');
  assert(source.includes('requestPersistentStorage'), 'Persistent storage is requested so a remembered folder handle is not evicted');
  assert(source.includes("committed=this.finishStore(store,'Remember the folder');store.put(handle,'workspace-directory');await committed"), 'Remembering the folder writes before waiting for the IndexedDB transaction to commit');
  assert(source.includes("committed=this.finishStore(store,'Forget the folder');store.delete('workspace-directory');await committed"), 'Forgetting a folder also mutates the active IndexedDB transaction before awaiting it');
  assert(source.includes("try{await storage.rememberHandle(directory);}catch"), 'A failed handle write cannot abort connecting a folder');
  assert(source.includes("state.mobileStage=isPortraitMobile()?(activeNote()?'editor':'notes'):'editor'"), 'Portrait launch opens the note itself, or the note list when there is no note');
  assert(!source.includes("?'workspace':'editor'"), 'Portrait launch no longer stops on the navigation drawer');
  const fluentOptions = /\.fluent-options \{([^}]*)\}/.exec(css);
  assert(fluentOptions, 'The fluent picker panel has a base rule');
  assert(/\bbottom\s*:/.test(fluentOptions[1]), 'The picker panel base rule pins its own bottom edge so a stray inset cannot collapse it');
  assert(!/\.fluent-options[^{]*\{[^}]*position\s*:\s*fixed/.test(css), 'No picker panel override can leak a fixed inset into the base rule');
  assert(!source.includes('serviceWorker')&&!fs.existsSync(path.join(projectRoot,'sw.js')), 'The installable app has no service worker or application cache');
  assert(html.includes('manifest.webmanifest?v=26') && html.includes('style.css?v=26') && html.includes('app.js?v=26'), 'Updated app resources receive a cache version');
  assert(html.includes('id="i-app-logo"') && (html.match(/href="#i-app-logo"/g)||[]).length===3, 'Startup and folder gates use the inline rounded brand mark');
  assert(!css.includes('background:url("icon.svg'), 'The splash mark does not wait for an external CSS background image');
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length, 'Static HTML IDs are unique');
  const localAssets = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(match => match[1].split('?')[0]).filter(value => value && !value.startsWith('#') && !/^[a-z]+:/i.test(value));
  localAssets.forEach(asset => assert(fs.existsSync(path.join(projectRoot, asset)), `Local asset exists: ${asset}`));
  assert(source.includes('const detectedLanguage = () =>'), 'Browser language is detected before a preference is saved');
  assert(source.includes("$('#collapseNav').onclick=toggleNavigationAndNotes"), 'The sole hamburger controls the primary and notes panes together');
  assert(source.includes("function toggleNavigationAndNotes(){const shell=$('.app-shell')"), 'Navigation and notes collapse in one atomic action');
  assert(source.includes('function activateNavigationScope(filter,folderId=null)'), 'Navigation items own the notes-pane toggle behavior');
  assert(source.includes("if(!isPortraitMobile()&&isCurrent){togglePane('notes');return;}"), 'Repeated desktop navigation selection toggles the notes pane');
  assert(source.includes("workSlot=$('#workMenuSlot')"), 'The sole hamburger moves into the editor after navigation is collapsed');
  assert(source.includes('function updateNoteCommandAvailability('), 'Selecting a newly created note refreshes command availability');
  assert(source.includes('updateNoteCommandAvailability(true);'), 'Newly selected notes immediately enable their note commands');
  assert(source.includes('function printInkDataUrl(note)'), 'Print output uses a dedicated ink renderer');
  assert(source.includes('drawStroke(context,stroke,1,false)'), 'Print ink resolves adaptive colors for a light paper background');
  assert(source.includes('if(vectors.length)vectors.forEach'), 'Print prefers theme-independent vector ink over the dark screen raster');
  assert(source.includes('normalizePrintTextColors(scene)'), 'Print converts explicit white editor text for a light paper background');
  assert(css.includes('color-scheme:light') && css.includes('background:#fff!important'), 'Print cards use a theme-independent light paper palette');
  assert(source.includes('function resumeRememberedFolder()'), 'A remembered folder can be reopened without showing the picker');
  assert(!source.includes('note.inkStrokes=normalizeLegacyInkErasers'), 'Workspace startup never performs a potentially blocking full ink migration');
  assert(source.includes("if(permission!=='granted'){await storage.forgetHandle();state.recalledDirectoryHandle=null"), 'A rejected remembered-folder permission cannot trap the folder gate');
  assert(source.includes("catch(error){console.error('Could not reopen remembered PowerMind folder',error);await storage.forgetHandle()"), 'An unavailable remembered folder falls back to a fresh folder choice');
  const editorMarkup = section('  function unifiedEditorBlockMarkup(', '  function openUnifiedSlashMenu(');
  assert(!editorMarkup.includes('secondary-block-handle') && !editorMarkup.includes('data-editor-delete'), 'Editor markup has no per-block drag or delete chrome');
  assert(!html.includes('id="openNotesMobile"') && !html.includes('id="openNav"'), 'Redundant hamburger buttons are removed');
  assert(source.includes('class="menu-check"'), 'Sort selection uses an icon checkmark, not a text character');
  let sequence = 0;
  const context = vm.createContext({
    id: () => `test-${++sequence}`, clone: value => JSON.parse(JSON.stringify(value)),
    state: {}, updateStorageLabel() {}, console,
    localStorage: { getItem: () => null, setItem() { throw new Error('Quota'); } },
    navigator: { storage: { getDirectory: async () => { throw new Error('Unavailable'); } } }
  });
  vm.runInContext(section('  function copyImportedNote(', '  async function importBackup('), context);
  const original = { id:'n', blocks:[{id:'b', text:'Body copy'}], ideas:[{id:'root',root:true},{id:'child',parentId:'root'}], editors:[{id:'e',blocks:[{id:'eb',text:'second editor'}]}], inkStrokes:[{id:'ink',points:[]}] };
  const imported = context.copyImportedNote(original, 'workspace', 'folder');
  assert.equal(imported.ideas[1].parentId, imported.ideas[0].id);
  assert.notEqual(imported.ideas[0].id, 'root');
  assert.notEqual(imported.editors[0].blocks[0].id, 'eb');
  assert.equal(original.ideas[1].parentId, 'root', 'Source backup remains unchanged');
  assert.equal(imported.editors[0].blocks[0].text, 'second editor');
  assert.equal(context.copyImportedNote({id:'minimal'}, 'w', 'f').workspaceId, 'w');
  context.clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
  context.safeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#c42b1c';
  context.safeDataImage=value=>/^data:image\/(?:png|jpe?g|webp|gif);base64,[a-z0-9+/=\s]+$/i.test(String(value||''))?String(value):'';
  context.sanitizeRichHtml=value=>String(value||'').replace(/<img[^>]*>/gi,'').replace(/\s+onclick=(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'');
  context.t=key=>key;
  context.normalizedId=(value,used)=>{let next=value||context.id();while(used.has(next))next=context.id();used.add(next);return next;};
  vm.runInContext(section('  function pointInPolygon(', '  function resolveInkColor('), context);
  vm.runInContext(section('  function findEditorPosition(', '  function firstMindMapPosition('), context);
  vm.runInContext(section('  function migrateDatabase(', '  function applyTranslations('), context);
  const normalized=context.migrateDatabase({version:3,workspaces:[{id:'w'}],folders:[{id:'f',workspaceId:'w'}],notes:[{id:'n',workspaceId:'w',folderId:'f',ink:'https://tracker.invalid/pixel.png',blocks:[{id:'b',type:'bad" onclick="alert(1)',color:'red" onmouseover="x',html:'<img src=x onerror=alert(1)><b onclick=alert(2)>safe</b>'},{id:'image',type:'image',src:'https://tracker.invalid/image.png'}],ideas:[{id:'r',root:true},{id:'a',parentId:'c'},{id:'c',parentId:'a'}]}]});
  assert.equal(normalized.notes[0].blocks[0].type,'text');
  assert.equal(normalized.notes[0].blocks[0].color,undefined);
  assert.equal(normalized.notes[0].blocks[0].html,'<b>safe</b>','Imported rich text is sanitized');
  assert.equal(normalized.notes[0].blocks[1].type,'text','External imported images are rejected');
  assert.equal(normalized.notes[0].ink,null,'External legacy ink images are rejected');
  assert.equal(normalized.notes[0].ideas[1].parentId,'r','Cyclic parent chain repaired');
  assert.equal(normalized.notes[0].card.x,620);
  assert(Array.isArray(normalized.notes[0].editors));
  const layoutNote={card:{x:100,y:100,width:620,height:410},editors:[{id:'e1',x:120,y:120,width:620,height:410,blocks:[]},{id:'e2',x:140,y:140,width:620,height:410,blocks:[]}]};
  context.repairEditorOverlaps(layoutNote);
  const boxes=[{x:100,y:100,width:620,height:410},...layoutNote.editors];
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert(boxes[i].x+boxes[i].width<=boxes[j].x||boxes[j].x+boxes[j].width<=boxes[i].x||boxes[i].y+boxes[i].height<=boxes[j].y||boxes[j].y+boxes[j].height<=boxes[i].y,'Editors do not overlap');
  vm.runInContext(section('  const storage = {', '  function seedDatabase()') + '\nthis.testStorage=storage;', context);
  await assert.rejects(context.testStorage.save({notes:[]}), /Choose a system folder/);
  const handleOps=[],handleStore={transaction:{},put(){handleOps.push('put');},delete(){handleOps.push('delete');}};
  context.testStorage.openHandleStore=async()=>handleStore;
  context.testStorage.finishStore=()=>{handleOps.push('listen');return Promise.resolve().then(()=>handleOps.push('commit'));};
  await context.testStorage.rememberHandle({name:'Notes'});
  await context.testStorage.forgetHandle();
  assert.deepEqual(handleOps,['listen','put','commit','listen','delete','commit'],'Folder handle transactions mutate before they complete');
  const makeDirectory=name=>{const entries=new Map();return{name,entries,queryPermission:async()=> 'granted',getDirectoryHandle:async(child,{create}={})=>{if(!entries.has(child)&&create)entries.set(child,makeDirectory(child));if(!entries.has(child))Object.assign(new Error('not found'),{name:'NotFoundError'});return entries.get(child);},getFileHandle:async(file,{create}={})=>{if(!entries.has(file)&&create)entries.set(file,{kind:'file',name:file,text:''});const record=entries.get(file);if(!record)throw Object.assign(new Error('not found'),{name:'NotFoundError'});return{getFile:async()=>({text:async()=>record.text}),createWritable:async()=>({write:async value=>{record.text=value;},close:async()=>{}})};},values:async function*(){for(const entry of entries.values())yield entry;},removeEntry:async key=>entries.delete(key)};};
  const directory=makeDirectory('Notes');context.state.directoryHandle=directory;
  const db={savedAt:20,notes:[{id:'recent',fileName:'Visible file',title:'Independent editor title'}],workspaces:[{id:'w'}],folders:[]};
  await context.testStorage.save(db);
  assert(directory.entries.has('powermind.workspace.json'),'Manifest is visible in selected folder');
  assert([...directory.entries.get('notes').entries.keys()].some(name=>name.includes('Visible file')&&name.endsWith('.powermind.json')),'Each note has a readable visible filename');
  const loaded=await context.testStorage.loadDirectory(directory);
  assert.equal(loaded.notes[0].fileName,'Visible file','Folder workspace round-trips the independent note filename');
  assert.equal(loaded.notes[0].title,'Independent editor title','Editor title remains independent from the note filename');
  const square=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];
  assert.equal(context.pointInPolygon({x:5,y:5},square),true);
  assert.equal(context.pointInPolygon({x:15,y:5},square),false);
  const inkLine={id:'line',mode:'pen',size:3,color:'#111111',points:[0,2,4,6,8,10,12,14,16,18,20].map(x=>({x,y:0,p:.5}))};
  assert.equal(context.strokeNearPoint(inkLine,{x:5,y:1},1),true,'Stroke eraser hits the segment between sampled points');
  assert.equal(context.strokeNearPoint(inkLine,{x:5,y:3},1),false,'Stroke eraser does not delete a nearby untouched stroke');
  const erased=context.eraseInkPath([inkLine],[{x:10,y:-2},{x:10,y:2}],1);
  assert.equal(erased.changed,true,'Point eraser cuts a vector stroke intersecting its visible path');
  assert.deepEqual(Array.from(erased.strokes,value=>Array.from(value.points,point=>point.x)),[[0,2,4,6],[14,16,18,20]],'Point eraser preserves clean vector fragments outside its visible radius');
  const untouched=context.eraseInkPath([inkLine],[{x:50,y:-2},{x:50,y:2}],1);
  assert.equal(untouched.changed,false,'Point eraser leaves nearby but untouched ink intact');
  assert.equal(untouched.strokes[0],inkLine,'Untouched strokes keep their original object and ordering');
  // --- Touch ink cost: Android gets a smaller buffer, Windows keeps the pen contract byte for byte ---
  assert(source.includes("function coarsePointer(){return matchMedia('(pointer:coarse)').matches;}"), 'Touch-only devices are identified through one shared helper');
  assert(source.includes("quality=canvas.id==='inkOverlay'?(touch?.6:1):clamp((window.devicePixelRatio||1)*state.view.zoom,1,touch?1:1.25)"), 'Touch devices cap the ink buffer at 1:1 while pen devices keep the sharper 1.25 cap');
  assert(html.includes('<canvas id="inkCanvas" width="1" height="1">'), 'The ink backing store is allocated on demand instead of at parse time');
  assert(html.includes('<canvas id="inkOverlay" width="1" height="1"'), 'The lasso overlay backing store is allocated on demand instead of at parse time');
  assert(/#inkCanvas\s*\{[^}]*width:\s*4000px[^}]*height:\s*3000px/.test(css), 'The ink canvas keeps its world-sized CSS box so a small backing store still covers the canvas');
  assert(/#inkOverlay\s*\{[^}]*width:\s*4000px[^}]*height:\s*3000px/.test(css), 'The overlay keeps its world-sized CSS box so a small backing store still covers the canvas');
  assert(source.includes("if(!hasContent){box.hidden=true;if(canvas.dataset.painted!=='1')return;"), 'Repainting the overlay is skipped entirely while nothing is painted on it');
  assert(source.includes("const painted=state.inkSelection.size>0||$('#inkOverlay').dataset.painted==='1'"), 'Starting a stroke only clears the overlay when something is painted on it');
  assert(source.includes('const rect=inkCanvasRect||(inkCanvasRect=canvas.getBoundingClientRect())'), 'Ink sampling reuses cached canvas bounds instead of forcing layout for every sample');
  assert(/strokeTouch=event\.pointerType==='touch';[^;]*guideSnap=null;inkCanvasRect=canvas\.getBoundingClientRect\(\);/.test(source), 'Each stroke distinguishes touch from pen, resets guide snapping, and refreshes cached bounds');
  assert(source.includes('inkCanvasRect = null;'), 'Pan, zoom and fit invalidate the cached ink bounds');
  assert(source.includes('transformFrame=requestAnimationFrame(apply)') && source.includes('translate3d('), 'Canvas transforms are coalesced to compositor animation frames');
  assert(source.includes('beginCanvasMotion()') && source.includes('endCanvasMotion(140)'), 'Pan, pinch and wheel interactions enter a temporary lightweight rendering state');
  assert(css.includes('.canvas-viewport.navigating .document-card') && css.includes('backdrop-filter:none!important'), 'Expensive Fluent effects pause only while the canvas is moving');
  assert(source.includes('const insertAtCaret=type=>') && source.includes('prefixProbe.cloneContents()') && source.includes('tailProbe.cloneContents()'), 'Ribbon elements split and insert at the live caret instead of appending to the document');
  assert(source.includes("button.onpointerdown=event=>{event.preventDefault();insertAtCaret(button.dataset.editorAdd);}"), 'Ribbon insertion preserves the editor selection before focus can leave the document');
  assert(source.includes("const editorScroll=new Map(") && source.includes("focus({preventScroll:true})"), 'Editor rerenders preserve internal scroll position and avoid jumping the document to its start');
  assert(source.includes("const compactPortraitQuery='(max-width: 1100px) and (orientation: portrait)'"), 'Phone and portrait-tablet hierarchy share one JavaScript breakpoint');
  assert((css.match(/@media \(max-width:1100px\) and \(orientation:portrait\)/g)||[]).length>=4, 'Portrait tablets receive the complete full-screen pane and touch layout');
  assert(source.includes("shell.classList.toggle('nav-collapsed',!compact&&") && source.includes("shell.classList.toggle('notes-collapsed',!compact&&"), 'Desktop pane-collapse preferences cannot hide a compact portrait stage');
  assert(css.includes('Desktop collapse preferences must never hide a full-screen mobile stage.') && css.includes('.app-shell.nav-collapsed .nav-pane,.app-shell.notes-collapsed .notes-pane'), 'Compact portrait CSS keeps every staged page visible despite stale desktop classes');
  assert(source.includes('palmLimit=coarse?140:24'), 'Finger contacts draw on touch-only devices while pen-first devices keep the original 24px palm rule');
  assert(source.includes("baseMinimum=source.pointerType==='pen'?.22:strokeTouch?1.2:.7"), 'The pen keeps its dense .22 sampling while touch strokes filter wider');
  assert(source.includes("const rawPointerSupported='onpointerrawupdate' in window") && source.includes('drawLiveInkSegment(context,stroke)'), 'Pen input uses raw updates and a constant-cost live segment path when available');
  assert(source.includes("state.storageMode='browser'") && source.includes("dataDb: 'ramizom.powermind.browser-data'"), 'Browsers without direct folder access use the IndexedDB workspace backend');
  assert(source.includes("if(state.storageMode==='browser')return await this.saveBrowser(db)") && source.includes("store.put(previous,'backup')"), 'Browser storage keeps an atomic current workspace plus a recovery snapshot');
  assert(source.includes("const nativeFolderAvailable = ()") && source.includes("typeof window.showDirectoryPicker === 'function'"), 'Direct-folder mode remains capability-gated for supporting Chrome and Edge environments');
  assert(html.includes('id="exportAllData"') && html.includes('id="importAllData"') && html.includes('id="browserImportInput"'), 'Portable whole-workspace backup controls are always available in settings');
  assert(source.includes('deleteCrossBlockSelection') && source.includes('mergeAtBoundary'), 'The continuous editor controls cross-line deletion and boundary merges without corrupting saved blocks');
  assert(source.includes("startsWith('eraser')?Math.max(baseMinimum,inkEraserRadius"), 'Wide erasers discard redundant sub-pixel samples without leaving gaps');
  assert(source.includes("if(source.pointerType==='pen')next.p=last.p*.58+next.p*.42"), 'Pen pressure is smoothed without delaying pointer coordinates');
  assert(source.includes("completed.mode==='eraser-pixel'"), 'Point erasing commits vector geometry instead of leaving a permanent raster mask');
  assert(source.includes('indexEraserPath(path,radius)'), 'Point eraser uses a spatial path index instead of scanning every eraser sample for every ink point');
  assert(source.includes("==='eraser'?'eraser-stroke':'lasso'"), 'The Windows pen side-button erase setting maps to the supported stroke eraser');
  assert(source.includes('requestEraseRender=()=>{if(eraseFrame)return;eraseFrame=requestAnimationFrame'), 'Whole-stroke erasing coalesces expensive canvas redraws to one per frame');
  assert(source.includes("state.tool==='ink'&&performance.now()<(state.penActiveUntil||0)"), 'Pen activity suppresses palm touches without disabling intentional two-finger navigation');
  assert(source.includes('state.cancelInkStroke?.();event.preventDefault();event.stopPropagation()'), 'Starting a two-finger ink gesture safely cancels the provisional finger stroke');
  assert(source.includes("if(event.pointerType==='mouse')updateInkCursor(event)"), 'Ink cursor styling is only touched by a mouse');
  assert(source.includes('coordinateFrame=requestAnimationFrame('), 'The canvas coordinate read-out is coalesced into one frame');
  // --- Mind map: selectable and draggable as a whole ---
  assert(source.includes('function ideaDragGroup(idea, note)'), 'The mind map has an explicit drag-group helper');
  assert(source.includes('if (!idea?.root) return null;'), 'Only the map root carries the whole map, so single nodes keep free positioning');
  assert(source.includes('group:()=>ideaDragGroup(idea,note)'), 'Idea nodes are wired to group dragging');
  assert(source.includes('options.onPointerDown?.(event)'), 'A drag can select its object before movement');
  assert(source.includes("onPointerDown:()=>selectObject('idea',idea.id,element)"), 'Grabbing an idea selects it, because preventDefault suppresses the follow-up click');
  assert(source.includes("window.addEventListener('pointermove',move,{passive:true})"), 'A drag tracks on window so a dropped pointer capture cannot strand a node');
  assert(source.includes('if(pointer.pointerId!==dragId)return;'), 'A stray second pointer cannot drive an active drag');
  assert(source.includes("window.removeEventListener('pointermove',move)"), 'Drag listeners are always removed when the drag ends');
  assert(source.includes('dragFrame=requestAnimationFrame(applyMove)'), 'Mind-map nodes and connections are committed together at most once per animation frame');
  assert(source.includes("path.setAttribute('d'") && source.includes('path.dataset.connectionId=idea.id'), 'Mind-map dragging updates stable SVG paths instead of rebuilding the entire connection layer');
  assert(!source.includes("element.addEventListener('pointermove',move)"), 'No drag binds its move handler to the dragged element');
  assert(css.includes('.idea-node.dragging {') && css.includes('.idea-node.group-dragging {'), 'Dragging a node or its whole map is visible');
  assert(source.includes('idea.width=clamp(Number(idea.width)||220,160,720)') && source.includes('data-idea-resize'), 'Mind-map node widths migrate safely and can be resized');
  assert(source.includes('<div class="idea-text">') && source.includes('<textarea aria-label="Idea" readonly>'), 'Long idea text wraps in display mode and uses a multiline editor');
  assert(css.includes('.idea-text{width:100%') && css.includes('.idea-resize{position:absolute'), 'Mind-map nodes show wrapping text and a visible resize affordance');
  assert(source.includes('const estimatedHeight=idea=>') && source.includes("parent.x+(parent.width||220)+gap"), 'Auto layout respects resized node widths and multiline idea height');
  console.log('PASS: syntax, unified editor path, import tree/IDs/content/source isolation, missing optional fields, system-folder storage, ink geometry, touch/pen ink cost split, mind-map group drag');
}
module.exports = run;
if (require.main === module) run().catch(error => { console.error(error); process.exitCode = 1; });
